language: android

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - platform-tools
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: true

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle